name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: cmake --preset release
    - name: Build
      run: cd build; ninja
    - name: Test
      run: ./build/Tests/UnitTests
